name: Node - SSH deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  # pull_request:
    # types:
      # - closed
    # branches:
      # - main

jobs:
  uses:
  # if_merged:
    # if: github.event.pull_request.merged == true
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
        
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14"

      - name: ðŸ”¨ Build Project
        run: |
          cd template
          yarn
          yarn build

      - name: ðŸ“‚ Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: "template/build/"
          REMOTE_HOST: 192.34.62.123
          REMOTE_USER: cicd-user
          TARGET: public_html/demos/admin-templates/datta-able/react/free
          EXCLUDE: "/template/dist/, /template/node_modules/"
